//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm loginForm;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl loginDiv;
		
		protected System.Web.UI.WebControls.Label userNameLbl;
		
		protected System.Web.UI.WebControls.TextBox userNameTbox;
		
		protected System.Web.UI.WebControls.Label passwordLbl;
		
		protected System.Web.UI.WebControls.TextBox passwordTbox;
		
		protected System.Web.UI.WebControls.Label alertLabel;
		
		protected System.Web.UI.WebControls.Button loginBtn;
		
		protected System.Web.UI.WebControls.LinkButton registerLink;
		
		protected System.Web.UI.WebControls.LinkButton forgotPasswordLink;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl registrationDiv;
		
		protected System.Web.UI.WebControls.Label firstNameLbl;
		
		protected System.Web.UI.WebControls.TextBox firstNameTbox;
		
		protected System.Web.UI.WebControls.Label lastNameLbl;
		
		protected System.Web.UI.WebControls.TextBox lasttNameTbox;
		
		protected System.Web.UI.WebControls.Label emailLbl;
		
		protected System.Web.UI.WebControls.TextBox emailTbox;
		
		protected System.Web.UI.WebControls.Label PhoneNumLbl;
		
		protected System.Web.UI.WebControls.TextBox PhoneNumTbox;
		
		protected System.Web.UI.WebControls.Label regPasswordLbl;
		
		protected System.Web.UI.WebControls.TextBox regPasswordTbox;
		
		protected System.Web.UI.WebControls.Label confPasswordLbl;
		
		protected System.Web.UI.WebControls.TextBox confPasswordTbox;
		
		protected System.Web.UI.WebControls.Label registrationAlertLabel;
		
		protected System.Web.UI.WebControls.LinkButton registrationLink;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl forgotPasswordDiv;
		
		protected System.Web.UI.WebControls.Label fpEmail;
		
		protected System.Web.UI.WebControls.TextBox fpEmailTbox;
		
		protected System.Web.UI.WebControls.LinkButton resetPasswordLink;
	}
}
